### ISSUE TITLE
Contrast is too low I think.

### ISSUE THREAD

**Issue by aasutossh** [sainnhe/everforest-vscode#1]
![image](https://user-images.githubusercontent.com/18498932/94099949-f2ef6900-fe4b-11ea-9f6c-2f2c72077b3f.png)

I've selected the "cartitem" inside `console.log`. Almost indistinguishable inside the string.

![image](https://user-images.githubusercontent.com/18498932/94100047-3518aa80-fe4c-11ea-90a2-2a6ee74e4e83.png)

This is the Ctrl-P results, contrast is quite low.
Can we do something about it?

**Comment by cyh0** [comment]
我遇到了差不多的问题，minimap的错误行提示显示的不太明显，特别是警告，得很仔细看才能发现它的存在，如果可以的话，略微提升一点对比度。
不过这个主题总体感觉很不错，在夜间主题里排我心目中的前二，像作者的其他主题一样，每个细节都几乎做到了完美，上一个给我同样感觉的是nord（有白色太刺眼的硬伤，不适合晚上用），从整体上看，完美符合它的名字：夜晚的森林，很美很静谧。

**Comment by sainnhe** [comment]
@aasutossh Sorry for late reply. My plan is to finish [everforest](https://github.com/sainnhe/everforest) (formally known as forest-night) which provides a light variant and an option to customize the background contrast. Then I'm going to optimize gruvbox-material-vscode, especially the semantic highlighting. After finish all of them, I'll rewrite this color scheme based on gruvbox-material-vscode, so please wait patiently.

---

@cyh0 我目前的计划是先完成 [everforest](https://github.com/sainnhe/everforest) 配色方案（以前叫做 forest-night），这个配色提供了一个亮色版本，并且有一个配置选项用来调整背景的对比度。然后我打算优化一下 gruvbox-material-vscode，尤其是优化语义高亮的部分。弄完了这些我在把 everforest 基于 gruvbox-material-vscode 的代码重写一遍。这可能需要一些时间，请耐心等待。

**Comment by aasutossh** [comment]
Will do sir. Thank you for your work.

**Comment by cyh0** [comment]
太好了，以后light也用这个主题了。

**Comment by sainnhe** [comment]
@aasutossh @cyh0 Done, you can install everforest from vscode marketplace or open-vsx registry.

**Comment by aasutossh** [comment]
> @aasutossh @cyh0 Done, you can install everforest from vscode marketplace or open-vsx registry.

Will check out ASAP.

**Comment by sainnhe** [comment]
@aasutossh The jetbrains theme is maintained in this repo: https://github.com/jef/forest-night-jetbrains

But the maintainer hasn't created a light variant yet.
