### ISSUE TITLE
Highlight not support for go generics

### ISSUE THREAD

**Issue by huibosa** [sainnhe/everforest-vscode#142]
![1648172704(1)](https://user-images.githubusercontent.com/78707242/160038270-12ed6195-49c9-46ac-9c49-a6f0dc53f68f.png)

Go has update to 1.18, everforest seems not provide a support for generics

**Comment by sainnhe** [comment]
<img width="1136" alt="截屏2022-03-26 下午5 06 43" src="https://user-images.githubusercontent.com/37491630/160232706-a176e4b9-816a-4b29-8548-fea78c83eb66.png">

I can't fix this because vscode doesn't support generics tokens.
