### ISSUE TITLE
Light theme, terminal color

### ISSUE THREAD

**Issue by cyh0** [sainnhe/everforest-vscode#2]
<img width="755" alt="屏幕截图 2021-04-23 131757" src="https://user-images.githubusercontent.com/59051928/115821975-58cdbe80-a436-11eb-9e46-2a539849741f.png">

有些白色的字体看不清。

**Comment by sainnhe** [comment]
这不是这个主题的问题，是 cargo 的问题。

有一些 shell 主题和命令行程序会使用 terminal.ansiWhite 来作为输出的前景色，这在黑色背景的情况下看起来比较正常，而一旦换成白色背景就会看不清。

所以建议你把这个 bug 报给 rust 那边，不过也有个办法可以临时修复，在 vscode settings.json 中把 terminal.ansiWhite 和 terminal.ansiBrightWhite 改成黑色，比如 `#000000` ，但这种做法可能会导致其它一些程序输出或 shell 主题看起来有问题。

**Comment by cyh0** [comment]
原来是这样。

**Comment by cyh0** [comment]
rust已经有issue了，好像解决了一些但没有完全解决，有些简单的light主题似乎不受影响。
