### ISSUE TITLE
Extension fails to load in vscode 1.78.2

### ISSUE THREAD

**Issue by rieger-jared** [sainnhe/everforest-vscode#200]
- Everforest Plugin version: v0.3.0
- Operating system/version: macOS Ventura Version 13.3.1 (a) (22E772610a)
- VSCode version: 
```
1.78.2
b3e4e68a0bc097f0ae7907b217c1119af9e03435
arm64
```

### Settings

None since I can't configure the plugin due to the bug.

### Steps to reproduce this bug

- Install plugin fresh
- Set to Everforest Dark from extension prompt
- See file does not exist.

### Actual behaviour

Unable to load file:///Users/jared/.vscode/extensions/sainnhe.everforest-0.3.0/themes/everforest-dark.json: Problems parsing JSON theme file: Value expected

When catting the file, it doesn't exist.

### Expected behaviour

I'm able to configure the `Dark Soft High Contrast` Theme and use the plugin.

**Comment by sainnhe** [comment]
I can't reproduce this bug in the same OS/Arch/Version.

This extension will modify the content in `themes/everforest-*.json` when config changes. It looks like vscode failed to write the file.

Did this bug appear before 1.78.2?
